/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DocumentRegistry {
  export type RegistroStruct = {
    contenidoHash: BytesLike;
    autor: AddressLike;
    timestamp: BigNumberish;
    tipo: string;
    referenciaId: string;
  };

  export type RegistroStructOutput = [
    contenidoHash: string,
    autor: string,
    timestamp: bigint,
    tipo: string,
    referenciaId: string
  ] & {
    contenidoHash: string;
    autor: string;
    timestamp: bigint;
    tipo: string;
    referenciaId: string;
  };
}

export interface DocumentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anclar"
      | "listaRegistros"
      | "obtenerRegistro"
      | "obtenerRegistros"
      | "registros"
      | "totalRegistros"
      | "verificar"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RegistroAnclado"): EventFragment;

  encodeFunctionData(
    functionFragment: "anclar",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "listaRegistros",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerRegistro",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerRegistros",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registros",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRegistros",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verificar",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "anclar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listaRegistros",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerRegistro",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerRegistros",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registros", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRegistros",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verificar", data: BytesLike): Result;
}

export namespace RegistroAncladoEvent {
  export type InputTuple = [
    registroId: BytesLike,
    contenidoHash: BytesLike,
    autor: AddressLike,
    timestamp: BigNumberish,
    tipo: string,
    referenciaId: string
  ];
  export type OutputTuple = [
    registroId: string,
    contenidoHash: string,
    autor: string,
    timestamp: bigint,
    tipo: string,
    referenciaId: string
  ];
  export interface OutputObject {
    registroId: string;
    contenidoHash: string;
    autor: string;
    timestamp: bigint;
    tipo: string;
    referenciaId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentRegistry;
  waitForDeployment(): Promise<this>;

  interface: DocumentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anclar: TypedContractMethod<
    [contenidoHash: BytesLike, tipo: string, referenciaId: string],
    [string],
    "nonpayable"
  >;

  listaRegistros: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  obtenerRegistro: TypedContractMethod<
    [registroId: BytesLike],
    [DocumentRegistry.RegistroStructOutput],
    "view"
  >;

  obtenerRegistros: TypedContractMethod<
    [offset: BigNumberish, limite: BigNumberish],
    [string[]],
    "view"
  >;

  registros: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string] & {
        contenidoHash: string;
        autor: string;
        timestamp: bigint;
        tipo: string;
        referenciaId: string;
      }
    ],
    "view"
  >;

  totalRegistros: TypedContractMethod<[], [bigint], "view">;

  verificar: TypedContractMethod<
    [registroId: BytesLike, contenidoHash: BytesLike],
    [
      [boolean, string, bigint] & {
        integro: boolean;
        autor: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anclar"
  ): TypedContractMethod<
    [contenidoHash: BytesLike, tipo: string, referenciaId: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listaRegistros"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "obtenerRegistro"
  ): TypedContractMethod<
    [registroId: BytesLike],
    [DocumentRegistry.RegistroStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "obtenerRegistros"
  ): TypedContractMethod<
    [offset: BigNumberish, limite: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "registros"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string] & {
        contenidoHash: string;
        autor: string;
        timestamp: bigint;
        tipo: string;
        referenciaId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalRegistros"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verificar"
  ): TypedContractMethod<
    [registroId: BytesLike, contenidoHash: BytesLike],
    [
      [boolean, string, bigint] & {
        integro: boolean;
        autor: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RegistroAnclado"
  ): TypedContractEvent<
    RegistroAncladoEvent.InputTuple,
    RegistroAncladoEvent.OutputTuple,
    RegistroAncladoEvent.OutputObject
  >;

  filters: {
    "RegistroAnclado(bytes32,bytes32,address,uint64,string,string)": TypedContractEvent<
      RegistroAncladoEvent.InputTuple,
      RegistroAncladoEvent.OutputTuple,
      RegistroAncladoEvent.OutputObject
    >;
    RegistroAnclado: TypedContractEvent<
      RegistroAncladoEvent.InputTuple,
      RegistroAncladoEvent.OutputTuple,
      RegistroAncladoEvent.OutputObject
    >;
  };
}
