/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DocumentRegistry {
  export type ActaStruct = {
    excursionId: string;
    destino: string;
    colonia: string;
    fecha: BigNumberish;
    totalAsistentes: BigNumberish;
    cupoMaximo: BigNumberish;
    coordinadorId: string;
    hashVerificacion: BytesLike;
    publicadoEn: BigNumberish;
  };

  export type ActaStructOutput = [
    excursionId: string,
    destino: string,
    colonia: string,
    fecha: bigint,
    totalAsistentes: bigint,
    cupoMaximo: bigint,
    coordinadorId: string,
    hashVerificacion: string,
    publicadoEn: bigint
  ] & {
    excursionId: string;
    destino: string;
    colonia: string;
    fecha: bigint;
    totalAsistentes: bigint;
    cupoMaximo: bigint;
    coordinadorId: string;
    hashVerificacion: string;
    publicadoEn: bigint;
  };
}

export interface DocumentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "actas"
      | "cambiarPublicador"
      | "listaActas"
      | "obtenerActa"
      | "obtenerActas"
      | "owner"
      | "publicador"
      | "publicarActa"
      | "totalActas"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ActaPublicada" | "PublicadorActualizado"
  ): EventFragment;

  encodeFunctionData(functionFragment: "actas", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "cambiarPublicador",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listaActas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerActa",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerActas",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "publicador",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicarActa",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalActas",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "actas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cambiarPublicador",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listaActas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "obtenerActa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerActas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "publicador", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicarActa",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalActas", data: BytesLike): Result;
}

export namespace ActaPublicadaEvent {
  export type InputTuple = [
    actaId: BytesLike,
    excursionId: string,
    destino: string,
    totalAsistentes: BigNumberish,
    publicadoEn: BigNumberish
  ];
  export type OutputTuple = [
    actaId: string,
    excursionId: string,
    destino: string,
    totalAsistentes: bigint,
    publicadoEn: bigint
  ];
  export interface OutputObject {
    actaId: string;
    excursionId: string;
    destino: string;
    totalAsistentes: bigint;
    publicadoEn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicadorActualizadoEvent {
  export type InputTuple = [anterior: AddressLike, nuevo: AddressLike];
  export type OutputTuple = [anterior: string, nuevo: string];
  export interface OutputObject {
    anterior: string;
    nuevo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DocumentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DocumentRegistry;
  waitForDeployment(): Promise<this>;

  interface: DocumentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  actas: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        excursionId: string;
        destino: string;
        colonia: string;
        fecha: bigint;
        totalAsistentes: bigint;
        cupoMaximo: bigint;
        coordinadorId: string;
        hashVerificacion: string;
        publicadoEn: bigint;
      }
    ],
    "view"
  >;

  cambiarPublicador: TypedContractMethod<
    [nuevo: AddressLike],
    [void],
    "nonpayable"
  >;

  listaActas: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  obtenerActa: TypedContractMethod<
    [actaId: BytesLike],
    [DocumentRegistry.ActaStructOutput],
    "view"
  >;

  obtenerActas: TypedContractMethod<
    [offset: BigNumberish, limite: BigNumberish],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  publicador: TypedContractMethod<[], [string], "view">;

  publicarActa: TypedContractMethod<
    [
      excursionId: string,
      destino: string,
      colonia: string,
      fecha: BigNumberish,
      totalAsistentes: BigNumberish,
      cupoMaximo: BigNumberish,
      coordinadorId: string,
      hashVerificacion: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  totalActas: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "actas"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint
      ] & {
        excursionId: string;
        destino: string;
        colonia: string;
        fecha: bigint;
        totalAsistentes: bigint;
        cupoMaximo: bigint;
        coordinadorId: string;
        hashVerificacion: string;
        publicadoEn: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cambiarPublicador"
  ): TypedContractMethod<[nuevo: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listaActas"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "obtenerActa"
  ): TypedContractMethod<
    [actaId: BytesLike],
    [DocumentRegistry.ActaStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "obtenerActas"
  ): TypedContractMethod<
    [offset: BigNumberish, limite: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publicador"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "publicarActa"
  ): TypedContractMethod<
    [
      excursionId: string,
      destino: string,
      colonia: string,
      fecha: BigNumberish,
      totalAsistentes: BigNumberish,
      cupoMaximo: BigNumberish,
      coordinadorId: string,
      hashVerificacion: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalActas"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ActaPublicada"
  ): TypedContractEvent<
    ActaPublicadaEvent.InputTuple,
    ActaPublicadaEvent.OutputTuple,
    ActaPublicadaEvent.OutputObject
  >;
  getEvent(
    key: "PublicadorActualizado"
  ): TypedContractEvent<
    PublicadorActualizadoEvent.InputTuple,
    PublicadorActualizadoEvent.OutputTuple,
    PublicadorActualizadoEvent.OutputObject
  >;

  filters: {
    "ActaPublicada(bytes32,string,string,uint32,uint64)": TypedContractEvent<
      ActaPublicadaEvent.InputTuple,
      ActaPublicadaEvent.OutputTuple,
      ActaPublicadaEvent.OutputObject
    >;
    ActaPublicada: TypedContractEvent<
      ActaPublicadaEvent.InputTuple,
      ActaPublicadaEvent.OutputTuple,
      ActaPublicadaEvent.OutputObject
    >;

    "PublicadorActualizado(address,address)": TypedContractEvent<
      PublicadorActualizadoEvent.InputTuple,
      PublicadorActualizadoEvent.OutputTuple,
      PublicadorActualizadoEvent.OutputObject
    >;
    PublicadorActualizado: TypedContractEvent<
      PublicadorActualizadoEvent.InputTuple,
      PublicadorActualizadoEvent.OutputTuple,
      PublicadorActualizadoEvent.OutputObject
    >;
  };
}
